import { ArrowRight, ArrowUpDown, ClipboardList, HeartHandshake, History, Loader2, Plus, RefreshCw, Sparkles, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { SiteHeader } from "@/components/SiteHeader";
import { categoryMeta, safeParseSkills } from "@/data/demo";
import { liveQueryOptions } from "@/lib/liveData";
import { trpc } from "@/lib/trpc";
import { ActivitySort, ActivityStatusFilter, filterAndSortActivity, summarizeActivity } from "@shared/activity";

type ActivityFilter = "all" | "request" | "offer";

const statusStyle = {
  open: "bg-stone-100 text-stone-700",
  matched: "bg-[#e9eee2] text-[#536645]",
  completed: "bg-emerald-100 text-emerald-800",
  closed: "bg-stone-200 text-stone-600",
} as const;

function ActivityHistorySkeleton() {
  return <div className="profile-skeleton-grid mt-7" aria-label="Loading activity history" role="status"><span className="sr-only">Loading your activity history</span>{[1, 2, 3].map(item => <div key={item} className="profile-skeleton-row"><span className="profile-skeleton-block h-10 w-10 rounded-xl" /><div className="min-w-0 flex-1 space-y-2"><span className="profile-skeleton-block block h-3 w-24 rounded" /><span className="profile-skeleton-block block h-4 w-3/4 rounded" /><span className="profile-skeleton-block block h-3 w-1/2 rounded" /></div><span className="profile-skeleton-block hidden h-3 w-16 rounded sm:block" /></div>)}</div>;
}

export default function Profile() {
  const [, setLocation] = useLocation();
  const { user, isAuthenticated, loading: authLoading } = useAuth();
  const { data: posts, isLoading, isFetching, error, refetch } = trpc.community.mine.useQuery(undefined, { enabled: isAuthenticated, ...liveQueryOptions });
  const [filter, setFilter] = useState<ActivityFilter>("all");
  const [statusFilter, setStatusFilter] = useState<ActivityStatusFilter>("all");
  const [sort, setSort] = useState<ActivitySort>("newest");
  const summary = useMemo(() => summarizeActivity(posts || []), [posts]);
  const visiblePosts = useMemo(() => filterAndSortActivity(posts || [], { kind: filter, status: statusFilter, sort }), [posts, filter, statusFilter, sort]);

  if (authLoading) return <div className="min-h-screen bg-[#fbfaf6]"><SiteHeader /><main className="container grid min-h-[60vh] place-items-center px-5 sm:px-7"><div className="flex items-center gap-3 text-sm font-bold text-stone-600"><Loader2 className="h-5 w-5 animate-spin text-[#536645]" />Opening your NeighborLift activity…</div></main></div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#fbfaf6] text-stone-900"><SiteHeader /><main className="container grid min-h-[65vh] place-items-center px-5 py-12 sm:px-7"><section className="max-w-xl rounded-[2rem] border border-stone-200 bg-white p-8 text-center shadow-[0_18px_45px_rgba(51,43,34,0.07)] sm:p-12"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e9eee2] text-[#536645]"><UserRound className="h-7 w-7" /></span><p className="section-kicker mt-6">Your NeighborLift profile</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">Keep your care history close.</h1><p className="mt-5 text-sm leading-6 text-stone-600">Sign in to see the help you have requested, the support you have offered, and the connections you have completed.</p><button onClick={() => startLogin()} className="mt-7 inline-flex items-center gap-2 rounded-full bg-stone-900 px-5 py-3 text-sm font-bold text-white transition hover:bg-[#536645] active:scale-[0.97]">Sign in to view my activity <ArrowRight className="h-4 w-4" /></button></section></main></div>;

  return <div className="min-h-screen bg-[#fbfaf6] text-stone-900"><SiteHeader /><main className="container px-5 py-9 sm:px-7 sm:py-14"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="section-kicker">Your NeighborLift profile</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-[-0.055em] text-stone-950 sm:text-5xl">Your history of showing up.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-stone-600">{user?.name ? `${user.name}, here is` : "Here is"} a private view of your past and current requests, offers, and completed assistance.</p></div><div className="flex gap-3"><button onClick={() => setLocation("/new/request")} className="rounded-full border border-stone-300 bg-white px-4 py-2.5 text-sm font-bold text-stone-800 transition hover:-translate-y-0.5 hover:border-stone-900 active:scale-[0.97]">Ask for help</button><button onClick={() => setLocation("/new/offer")} className="inline-flex items-center gap-2 rounded-full bg-stone-900 px-4 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#536645] active:scale-[0.97]"><Plus className="h-4 w-4" />Offer support</button></div></div>
    <section className="mt-9 grid gap-4 sm:grid-cols-3"><div className="profile-summary-card bg-[#e9eee2]"><ClipboardList className="h-5 w-5 text-[#536645]" /><p className="mt-7 text-sm font-bold text-[#536645]">Requests shared</p><p className="mt-1 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">{summary.requests}</p></div><div className="profile-summary-card bg-[#f5eee1]"><HeartHandshake className="h-5 w-5 text-[#987034]" /><p className="mt-7 text-sm font-bold text-[#775d38]">Offers shared</p><p className="mt-1 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">{summary.offers}</p></div><div className="profile-summary-card bg-[#ece9f3]"><Sparkles className="h-5 w-5 text-[#685989]" /><p className="mt-7 text-sm font-bold text-[#5f5578]">Support completed</p><p className="mt-1 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">{summary.completed}</p></div></section>
    <section className="mt-8 rounded-[1.7rem] border border-stone-200 bg-white p-5 shadow-[0_14px_36px_rgba(51,43,34,0.05)] sm:p-7"><div className="flex flex-col gap-5"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><History className="h-4 w-4 text-[#536645]" /><h2 className="font-display text-2xl font-bold tracking-[-0.04em] text-stone-950">Your activity</h2></div><p className="mt-1 text-sm text-stone-600">A private record of the needs you shared and the support you offered.</p><p className="live-status mt-2" aria-live="polite"><span className="live-dot" />{isFetching ? "Refreshing your activity…" : "Private activity stays current while you are here"}</p></div><div className="flex flex-wrap items-center gap-2">{(["all", "request", "offer"] as const).map(item => <button key={item} onClick={() => setFilter(item)} aria-pressed={filter === item} className={`filter-chip ${filter === item ? "filter-chip-active" : ""}`}>{item === "all" ? "All activity" : item === "request" ? "Requests" : "Offers"}</button>)}<button onClick={() => void refetch()} disabled={isFetching} aria-label="Refresh activity" className="grid h-8 w-8 place-items-center rounded-full border border-stone-200 text-stone-600 transition hover:border-[#71865f] hover:text-[#536645] active:scale-95 disabled:opacity-50"><RefreshCw className={`h-3.5 w-3.5 ${isFetching ? "animate-spin" : ""}`} /></button></div></div><div className="flex flex-col gap-3 border-t border-stone-100 pt-5 sm:flex-row sm:items-end sm:justify-between"><fieldset><legend className="text-xs font-bold uppercase tracking-[0.12em] text-stone-500">Progress</legend><div className="mt-2 flex flex-wrap gap-2">{(["all", "open", "matched", "completed"] as const).map(item => <button key={item} onClick={() => setStatusFilter(item)} aria-pressed={statusFilter === item} className={`filter-chip ${statusFilter === item ? "filter-chip-active" : ""}`}>{item === "all" ? "Any status" : item[0].toUpperCase() + item.slice(1)}</button>)}</div></fieldset><label className="grid gap-2 text-xs font-bold uppercase tracking-[0.12em] text-stone-500"><span className="flex items-center gap-1.5"><ArrowUpDown className="h-3.5 w-3.5" />Sort activity</span><select aria-label="Sort activity" value={sort} onChange={event => setSort(event.target.value as ActivitySort)} className="rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-sm font-bold normal-case tracking-normal text-stone-800 shadow-sm outline-none transition hover:border-[#71865f] focus:border-[#70855e] focus:ring-4 focus:ring-[#dce6d1]"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="status">Active status first</option></select></label></div></div>
      {!isLoading && !error && <p aria-live="polite" className="mt-5 text-xs font-semibold text-stone-500">Showing {visiblePosts.length} {visiblePosts.length === 1 ? "activity item" : "activity items"} · {sort === "newest" ? "newest first" : sort === "oldest" ? "oldest first" : "active status first"}</p>}
      {isLoading && <ActivityHistorySkeleton />}
      {error && <div role="alert" className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>Your history could not be loaded.</strong> Please refresh the page. Your posts have not been changed.</div>}
      {!isLoading && !error && visiblePosts.length === 0 && <div className="grid place-items-center py-16 text-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#f1f4ed] text-[#536645]"><HeartHandshake className="h-6 w-6" /></span><h3 className="mt-5 font-display text-2xl font-bold text-stone-950">Your activity is ready when you are.</h3><p className="mt-2 max-w-md text-sm leading-6 text-stone-600">{filter === "all" ? "Share a small request or offer to begin your NeighborLift history." : `You have not shared any ${filter === "request" ? "requests" : "offers"} yet.`}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/new/request" className="rounded-full bg-stone-900 px-4 py-2.5 text-sm font-bold text-white">Ask for help</Link><Link href="/new/offer" className="rounded-full border border-stone-300 px-4 py-2.5 text-sm font-bold text-stone-800">Offer support</Link></div></div>}
      {!isLoading && !error && visiblePosts.length > 0 && <div className="mt-5 space-y-2">{visiblePosts.map(post => { const category = categoryMeta[post.category]; const skills = safeParseSkills(post.skills); return <Link key={post.id} href={`/help/${post.id}`} className="activity-row group"><div className="flex min-w-0 items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-bold transition duration-200 group-hover:scale-105 ${category.color}`}>{category.emoji}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-[0.12em] text-stone-500">{post.kind === "request" ? "Help request" : "Neighbor offer"}</span><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusStyle[post.status]}`}>{post.status}</span></div><h3 className="mt-1 truncate text-sm font-bold text-stone-900 transition group-hover:text-[#536645]">{post.title}</h3><p className="mt-1 text-xs text-stone-500">{category.label} · {skills.slice(0, 2).join(", ") || "No skills listed"}</p></div></div><div className="flex shrink-0 items-center justify-between gap-4 pl-[3.25rem] sm:pl-0"><span className="text-xs font-medium text-stone-500">{new Date(post.createdAt).toLocaleDateString()}</span><ArrowRight className="h-4 w-4 text-[#536645] transition duration-200 group-hover:translate-x-1" /></div></Link>; })}</div>}
    </section></main></div>;
}
