import { ArrowRight, ClipboardList, HeartHandshake, History, Loader2, Plus, Sparkles, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { SiteHeader } from "@/components/SiteHeader";
import { categoryMeta, safeParseSkills } from "@/data/demo";
import { trpc } from "@/lib/trpc";
import { summarizeActivity } from "@shared/activity";

type ActivityFilter = "all" | "request" | "offer";

const statusStyle = {
  open: "bg-stone-100 text-stone-700",
  matched: "bg-[#e9eee2] text-[#536645]",
  completed: "bg-emerald-100 text-emerald-800",
  closed: "bg-stone-200 text-stone-600",
} as const;

export default function Profile() {
  const [, setLocation] = useLocation();
  const { user, isAuthenticated, loading: authLoading } = useAuth();
  const { data: posts, isLoading, error } = trpc.community.mine.useQuery(undefined, { enabled: isAuthenticated });
  const [filter, setFilter] = useState<ActivityFilter>("all");
  const summary = useMemo(() => summarizeActivity(posts || []), [posts]);
  const visiblePosts = (posts || []).filter(post => filter === "all" || post.kind === filter);

  if (authLoading) return <div className="min-h-screen bg-[#fbfaf6]"><SiteHeader /><main className="container grid min-h-[60vh] place-items-center px-5 sm:px-7"><div className="flex items-center gap-3 text-sm font-bold text-stone-600"><Loader2 className="h-5 w-5 animate-spin text-[#536645]" />Opening your NeighborLift activity…</div></main></div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#fbfaf6] text-stone-900"><SiteHeader /><main className="container grid min-h-[65vh] place-items-center px-5 py-12 sm:px-7"><section className="max-w-xl rounded-[2rem] border border-stone-200 bg-white p-8 text-center shadow-[0_18px_45px_rgba(51,43,34,0.07)] sm:p-12"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e9eee2] text-[#536645]"><UserRound className="h-7 w-7" /></span><p className="section-kicker mt-6">Your NeighborLift profile</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">Keep your care history close.</h1><p className="mt-5 text-sm leading-6 text-stone-600">Sign in to see the help you have requested, the support you have offered, and the connections you have completed.</p><button onClick={() => startLogin()} className="mt-7 inline-flex items-center gap-2 rounded-full bg-stone-900 px-5 py-3 text-sm font-bold text-white transition hover:bg-[#536645]">Sign in to view my activity <ArrowRight className="h-4 w-4" /></button></section></main></div>;

  return <div className="min-h-screen bg-[#fbfaf6] text-stone-900"><SiteHeader /><main className="container px-5 py-9 sm:px-7 sm:py-14"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="section-kicker">Your NeighborLift profile</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-[-0.055em] text-stone-950 sm:text-5xl">Your history of showing up.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-stone-600">{user?.name ? `${user.name}, here is` : "Here is"} a private view of your past and current requests, offers, and completed assistance.</p></div><div className="flex gap-3"><button onClick={() => setLocation("/new/request")} className="rounded-full border border-stone-300 bg-white px-4 py-2.5 text-sm font-bold text-stone-800 transition hover:border-stone-900">Ask for help</button><button onClick={() => setLocation("/new/offer")} className="inline-flex items-center gap-2 rounded-full bg-stone-900 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-[#536645]"><Plus className="h-4 w-4" />Offer support</button></div></div>
    <section className="mt-9 grid gap-4 sm:grid-cols-3"><div className="rounded-[1.5rem] bg-[#e9eee2] p-6"><ClipboardList className="h-5 w-5 text-[#536645]" /><p className="mt-7 text-sm font-bold text-[#536645]">Requests shared</p><p className="mt-1 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">{summary.requests}</p></div><div className="rounded-[1.5rem] bg-[#f5eee1] p-6"><HeartHandshake className="h-5 w-5 text-[#987034]" /><p className="mt-7 text-sm font-bold text-[#775d38]">Offers shared</p><p className="mt-1 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">{summary.offers}</p></div><div className="rounded-[1.5rem] bg-[#ece9f3] p-6"><Sparkles className="h-5 w-5 text-[#685989]" /><p className="mt-7 text-sm font-bold text-[#5f5578]">Support completed</p><p className="mt-1 font-display text-4xl font-extrabold tracking-[-0.05em] text-stone-950">{summary.completed}</p></div></section>
    <section className="mt-8 rounded-[1.7rem] border border-stone-200 bg-white p-5 shadow-[0_14px_36px_rgba(51,43,34,0.05)] sm:p-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><History className="h-4 w-4 text-[#536645]" /><h2 className="font-display text-2xl font-bold tracking-[-0.04em] text-stone-950">Your activity</h2></div><p className="mt-1 text-sm text-stone-600">A private record of the needs you shared and the support you offered.</p></div><div className="flex flex-wrap gap-2">{(["all", "request", "offer"] as const).map(item => <button key={item} onClick={() => setFilter(item)} className={`filter-chip ${filter === item ? "filter-chip-active" : ""}`}>{item === "all" ? "All activity" : item === "request" ? "Requests" : "Offers"}</button>)}</div></div>
      {isLoading && <div className="flex items-center gap-2 py-16 text-sm font-semibold text-stone-500"><Loader2 className="h-4 w-4 animate-spin" />Loading your history…</div>}
      {error && <div role="alert" className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>Your history could not be loaded.</strong> Please refresh the page. Your posts have not been changed.</div>}
      {!isLoading && !error && visiblePosts.length === 0 && <div className="grid place-items-center py-16 text-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#f1f4ed] text-[#536645]"><HeartHandshake className="h-6 w-6" /></span><h3 className="mt-5 font-display text-2xl font-bold text-stone-950">Your activity is ready when you are.</h3><p className="mt-2 max-w-md text-sm leading-6 text-stone-600">{filter === "all" ? "Share a small request or offer to begin your NeighborLift history." : `You have not shared any ${filter === "request" ? "requests" : "offers"} yet.`}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/new/request" className="rounded-full bg-stone-900 px-4 py-2.5 text-sm font-bold text-white">Ask for help</Link><Link href="/new/offer" className="rounded-full border border-stone-300 px-4 py-2.5 text-sm font-bold text-stone-800">Offer support</Link></div></div>}
      {!isLoading && !error && visiblePosts.length > 0 && <div className="mt-7 divide-y divide-stone-100">{visiblePosts.map(post => { const category = categoryMeta[post.category]; const skills = safeParseSkills(post.skills); return <Link key={post.id} href={`/help/${post.id}`} className="group flex flex-col gap-4 py-5 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-bold ${category.color}`}>{category.emoji}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-[0.12em] text-stone-500">{post.kind === "request" ? "Help request" : "Neighbor offer"}</span><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusStyle[post.status]}`}>{post.status}</span></div><h3 className="mt-1 truncate text-sm font-bold text-stone-900 transition group-hover:text-[#536645]">{post.title}</h3><p className="mt-1 text-xs text-stone-500">{category.label} · {skills.slice(0, 2).join(", ") || "No skills listed"}</p></div></div><div className="flex shrink-0 items-center justify-between gap-4 pl-[3.25rem] sm:pl-0"><span className="text-xs font-medium text-stone-500">{new Date(post.createdAt).toLocaleDateString()}</span><ArrowRight className="h-4 w-4 text-[#536645]" /></div></Link>; })}</div>}
    </section></main></div>;
}
